name: inkdrop
summary: Note-taking App with Robust Markdown Editor
description: |
  Inkdrop enables hackers to keep track of their daily progress when it comes to hacking in one convenient spot without having to rely on traditional word processors.
  Inkdrop features support for Markdown with the ability to do code syntax highlighting as well as built-in syncing capabilities.
  You can organize your progress in a clean, uniform way that's focused on ensuring that the information is easy to work through and can be read uniformly.
grade: stable
base: core18
confinement: strict
adopt-info: inkdrop

architectures:
  - build-on: amd64

parts:
  inkdrop:
    plugin: dump
    #source: https://api.inkdrop.app/download/linux/deb?pre=1
    source: https://inkdrop-dist.s3-ap-northeast-1.amazonaws.com/v5.4.3/inkdrop_5.4.3_amd64.deb
    source-type: deb
    override-pull: |
      set -x
      snapcraftctl pull
      #DEB_API="https://api.inkdrop.app/download/linux/deb?pre=1"
      #DEB_URL=$(curl -w "%{url_effective}\n" -I -L -s -S "${DEB_API}" -o /dev/null)
      #VERSION=$(echo "${DEB_URL}" | cut -d'/' -f4 | tr -d 'v')
      VERSION="5.4.3"
      snapcraftctl set-version $VERSION
    override-build: |
      set -x
      snapcraftctl build
      # Correct path to icon.
      grep Icon $SNAPCRAFT_PART_INSTALL/usr/share/applications/inkdrop.desktop
      sed -i 's|Icon=inkdrop|Icon=/usr/share/pixmaps/inkdrop\.png|g' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/inkdrop.desktop
      sed -i 's|%U|--no-sandbox %U|' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/inkdrop.desktop
      grep Icon $SNAPCRAFT_PART_INSTALL/usr/share/applications/inkdrop.desktop
    prime:
      - -usr/lib/inkdrop/chrome-sandbox
    build-packages:
      - curl
    stage-packages:
      - libcanberra-gtk-module
      - libcanberra-gtk3-module
      - libgles2-mesa
      - gnome-keyring
      - libsecret-1-0
      - libglu1-mesa
      - libxkbfile1
      - libasound2
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6
      - libpcre2-8-0

apps:
  inkdrop:
    command: usr/bin/inkdrop --no-sandbox
    extensions: [gnome-3-28]
    desktop: usr/share/applications/inkdrop.desktop
    environment:
      DISABLE_WAYLAND: "1"
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - alsa
      - avahi-observe
      - browser-support
      - camera
      - cups-control
      - gsettings
      - home
      - network
      - opengl
      - audio-playback
      - pulseaudio
      - screen-inhibit-control
      - upower-observe
      - password-manager-service
  ipm:
    command: usr/lib/inkdrop/resources/app/ipm/bin/ipm
    plugs:
      - gsettings
      - home
      - mount-observe
      - network
      - password-manager-service
